### ISSUE TITLE
[feature] Thumbs up bot

### ISSUE THREAD

**Issue by nikgil** [cscareerhub/megabot#140]
### Is your feature request related to a problem? Please describe

Auto add thumbs up for questions

### Describe the solution you'd like

Thumbs up whenever someone comments in a specific channel (ad hoc for AMA)

### Describe alternatives you've considered

Currently have to manually do it by mod

**Comment by brendacs** [comment]
@nikgil We also need this for the changelog - but that one is auto-thumbs up _and_ thumbs down. Can we make them both be in one bot that does it for both of those channels? Or better yet - make it so mods are able to configure which channels it does this for and whether to do up and down or just up?
