### ISSUE TITLE
[feature] Limit pinning to specific roles

### ISSUE THREAD

**Issue by brendacs** [cscareerhub/megabot#29]
### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

relates to #25

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by sirNikolai** [comment]
@brendacs was this one not done already? I believe you made the contributor & mod perm check

**Comment by brendacs** [comment]
> @brendacs was this one not done already? I believe you made the contributor & mod perm check

@sirNikolai Yeah gopher mentioned, thought he closed. Closing now
