### ISSUE TITLE
[feature] Add LICENSE.md and license badge

### ISSUE THREAD

**Issue by sirNikolai** [cscareerhub/megabot#55]
### Is your feature request related to a problem? Please describe

Project license is [MIT](https://choosealicense.com/licenses/mit/).
This should be reflected in a LICENSE.md and a badge in README.md

### Describe the solution you'd like

Add MIT license info to LICENSE.md and README.md

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by ST0RM2** [comment]
can i work on this ?

**Comment by brendacs** [comment]
@ST0RM2 Yes, go ahead. I'll assign you. :)
