### ISSUE TITLE
[feature] Add relevant badges

### ISSUE THREAD

**Issue by sirNikolai** [cscareerhub/megabot#57]
### Is your feature request related to a problem? Please describe

Following badges should be added to the README.md:
- [ ] Discord
- [ ] Testing state
- [x] License (linked to #55)

### Describe the solution you'd like

- Discord should look similar to: ![image](https://user-images.githubusercontent.com/1833579/101721639-71849b80-3a76-11eb-86bd-2e870f049e6c.png)

- Testing state should look similar to: ![image](https://user-images.githubusercontent.com/1833579/101721609-5ca80800-3a76-11eb-9963-903bf7b1d054.png)

### Describe alternatives you've considered

N/A

### Additional context

More badges will be added if required

**Comment by andrewtdiz** [comment]
Does making the Discord badge require permissions of a channel admin?

**Comment by andrewtdiz** [comment]
I'll get this added today
