### ISSUE TITLE
[feature] Limit development bot to specific channels

### ISSUE THREAD

**Issue by sirNikolai** [cscareerhub/megabot#89]
### Is your feature request related to a problem? Please describe

Given we will have 2 instances of megabot on server we need to sandbox one to bot-commands channel.

### Describe the solution you'd like

Add some conditionals to bot.
Prefix should be changed in settings.

### Describe alternatives you've considered

Changing prefix alone will not be enough to mitigate this since some stuff (like pins) are reaction based and therefore need to be sandboxed separately anyway

### Additional context

N/A

**Comment by brendacs** [comment]
resolved by https://github.com/cscareerhub/megabot/pull/91
